# Generated by Django 4.1.1 on 2022-10-12 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EcommerceApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_ext',
            name='district',
            field=models.CharField(default='null', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user_ext',
            name='state',
            field=models.CharField(default='null', max_length=255),
            preserve_default=False,
        ),
    ]
