# Generated by Django 4.1.1 on 2022-10-12 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EcommerceApp', '0003_user_ext_otp'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_ext',
            name='pincode',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
