# Generated by Django 4.1.1 on 2022-10-14 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EcommerceApp', '0007_kart'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='amount',
            field=models.IntegerField(default='0'),
            preserve_default=False,
        ),
    ]
